<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT emu_command (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
	<datafile>
		<header>
			<emu_name>Atari 7800</emu_name>
			<emu_parser>NoIntro_parser.xml</emu_parser>
			<emu_description>Atari 7800</emu_description>
			<emu_category>Atari</emu_category>
			<emu_version>100215</emu_version>
			<emu_date>10/02/2015</emu_date>
			<emu_author>Zach Morris</emu_author>
			<emu_homepage>http://www.no-intro.org</emu_homepage>
			<emu_baseurl>https://archive.org/download/</emu_baseurl>
			<emu_launcher>external</emu_launcher>
			<emu_ext_launch_cmd>"%APP_PATH%\retroarch.exe" %NETPLAY_COMMAND% -L "%APP_PATH%\cores\prosystem_libretro.dll" "%ROM_PATH%"</emu_ext_launch_cmd>
			<emu_downloadpath>default</emu_downloadpath>
			<emu_postdlaction>none</emu_postdlaction>
			<emu_comment>Internet Archives Atari 7800 Collection.

The Atari 7800 ProSystem, or simply the Atari 7800, is a home video game console officially released by Atari Corporation in 1986.  It had simple digital joysticks and was almost fully backward-compatible with the Atari 2600, the first console to have backward compatibility without the use of additional modules. It was considered affordable at a price of US$140.

Developer:  Atari

CPU:  Atari SALLY 6502 ("6502C")

Memory:  4KB RAM

Graphics:  MARIA

Sound:  Pot Keyboard Integrated Circuit

Display:  320Ã—240

Media:  Cartridge

Max Controllers:  2</emu_comment>
			<emu_thumb>special://home/addons/plugin.program.iarl/resources/skins/Default/media/27-1.jpg</emu_thumb>
			<emu_banner>http://thegamesdb.net/banners/platform/banners/27-2.jpg</emu_banner>
			<emu_fanart>https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Atari-7800-Console-Set.jpg/1280px-Atari-7800-Console-Set.jpg</emu_fanart>
			<emu_logo>https://www.launchbox-app.com/wp-content/sp-resources/forum-image-uploads/bd00/2015/05/_thumbs/_Atari-7800-1.png</emu_logo>
			<emu_trailer>Oxfsb1wvWb8</emu_trailer>
		</header>
			<game name="Asteroids (1987)(Atari)(NTSC)">
					<rom name="Asteroids_1987_Atari_NTSC/Asteroids_1987_Atari_NTSC.a78" size="0"/>
					<description>Asteroids (1987)(Atari)(NTSC)</description>
					<snapshot1>https://archive.org/serve/Asteroids_1987_Atari_NTSC/Asteroids_1987_Atari_NTSC_screenshot.png</snapshot1>
					<plot>Start blasting! It's your only way out of this cloud of hurtling astral bodies. Peripheral vision. Lightning reflexes. And cool control. That's what it takes to save your ship. And your life!

 - 8 waves of devastating asteroids.
 - For 1 or 2 players.
 - Competing player ships can appear on screen simultaneously.</plot>
					<genre>ActionShooter</genre>
					<releasedate>11/01/1987</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/18177-1.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/27258-asteroids-atari-7800-front-cover.jpg</boxart2>
					<boxart3>http://thegamesdb.net/banners/boxart/original/back/18177-1.jpg</boxart3>
					<boxart4>http://www.mobygames.com/images/covers/l/27259-asteroids-atari-7800-back-cover.jpg</boxart4>
					<boxart5>http://www.mobygames.com/images/covers/l/27260-asteroids-atari-7800-media.jpg</boxart5>
					<snapshot1>http://thegamesdb.net/banners/screenshots/18177-1.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/54985-asteroids-atari-7800-screenshot-atari-logo.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/54986-asteroids-atari-7800-screenshot-title-screen.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/54987-asteroids-atari-7800-screenshot-a-game-in-progress.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/54988-asteroids-atari-7800-screenshot-watch-out-for-that-flying-saucer.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/54989-asteroids-atari-7800-screenshot-each-level-begins-with-large.jpg</snapshot6>
			</game>
			<game name="Double Dragon (1989)(Activision)(NTSC)">
					<rom name="Double_Dragon_1989_Activision_NTSC/Double_Dragon_1989_Activision_NTSC.a78" size="0"/>
					<description>Double Dragon (1989)(Activision)(NTSC)</description>
					<snapshot1>https://archive.org/serve/Double_Dragon_1989_Activision_NTSC/Double_Dragon_1989_Activision_NTSC_screenshot.png</snapshot1>
					<plot>Twin brothers Billy and Jimmy Lee learned to fight the hard way -- for survival in the unforgiving city streets. Their brand of combat -- classic martial arts maneuvers mixed with anything-goes street brawling -- has turned them into walking lethal weapons.

Now, the Lees must summon all their fighting abilities and cunning into meeting the greatest challenge of their lives -- rescuing Billy's girlfriend, Marion.  She's been kidnapped by the Black Warriors, the savage street gang led by the mysterious Shadow Boss.

The twins pursue the Black Warriors through the city streets and its outskirts.  Finally they fight their way into the Secret Enemy Base.  There, Billy and Jimmy meet the Shadow Boss.  It's a battle to the finish, with Marion as the prize!</plot>
					<genre>Platform</genre>
					<releasedate>01/01/1989</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/21041-1.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/27307-double-dragon-atari-7800-front-cover.jpg</boxart2>
					<boxart3>http://thegamesdb.net/banners/boxart/original/back/21041-1.jpg</boxart3>
					<boxart4>http://www.mobygames.com/images/covers/l/27308-double-dragon-atari-7800-back-cover.jpg</boxart4>
					<boxart5>http://www.mobygames.com/images/covers/l/27309-double-dragon-atari-7800-media.jpg</boxart5>
					<snapshot1>http://www.mobygames.com/images/shots/l/55260-double-dragon-atari-7800-screenshot-atari-logo.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/55261-double-dragon-atari-7800-screenshot-title-screen.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/55262-double-dragon-atari-7800-screenshot-beginning-the-game.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/55263-double-dragon-atari-7800-screenshot-outnumbered-as-usual.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/55264-double-dragon-atari-7800-screenshot-watch-out-for-that-whip.jpg</snapshot5>
			</game>
			<game name="Kung-Fu Master (1989)(Absolute Entertainment)(NTSC)">
					<rom name="Kung-Fu_Master_1989_Absolute_Entertainment_NTSC/Kung-Fu_Master_1989_Absolute_Entertainment_NTSC.a78" size="0"/>
					<description>Kung-Fu Master (1989)(Absolute Entertainment)(NTSC)</description>
					<snapshot1>https://archive.org/serve/Kung-Fu_Master_1989_Absolute_Entertainment_NTSC/Kung-Fu_Master_1989_Absolute_Entertainment_NTSC_screenshot.png</snapshot1>
					<plot>The gorgeous Princess Victoria is imprisoned in the Evil Wizard's Temple.  As Kung-Fu Master, you must free her.  Unfortunately, the Temple's five tortuous levels are seething with menacing foes. 

Smash your way through one level and start the next with a renewed energy meter and timer. Once you free your Princess, it's back to the beginning where your foes return faster and nastier.</plot>
					<genre>Action</genre>
					<releasedate>06/01/1989</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/21102-1.jpg</boxart1>
					<snapshot1>http://thegamesdb.net/banners/screenshots/21102-1.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/194379-kung-fu-master-atari-7800-screenshot-title-screen.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/194380-kung-fu-master-atari-7800-screenshot-dagger-thrower-on-first.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/194381-kung-fu-master-atari-7800-screenshot-you-ll-get-tired-of-these.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/194382-kung-fu-master-atari-7800-screenshot-first-floor-boss.jpg</snapshot5>
			</game>
			<game name="Rampage (1989)(Activision)(NTSC)">
					<rom name="Rampage_1989_Activision_NTSC/Rampage_1989_Activision_NTSC.a78" size="0"/>
					<description>Rampage (1989)(Activision)(NTSC)</description>
					<snapshot1>https://archive.org/serve/Rampage_1989_Activision_NTSC/Rampage_1989_Activision_NTSC_screenshot.png</snapshot1>
					<plot>Based on the 1985 Bally Midway coin-op, the 7800 was produced by Activision and distributed by Mediagenic. This is a movie-monster game in which you control the beasts and destroy the city.</plot>
					<genre>Action</genre>
					<releasedate>01/01/1988</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/22383-1.jpg</boxart1>
					<boxart2>http://thegamesdb.net/banners/boxart/original/back/22383-1.jpg</boxart2>
					<boxart3>http://www.mobygames.com/images/covers/l/295649-rampage-atari-7800-media.jpg</boxart3>
					<snapshot1>http://thegamesdb.net/banners/screenshots/22383-1.jpg</snapshot1>
					<snapshot2>http://thegamesdb.net/banners/screenshots/22383-2.jpg</snapshot2>
					<snapshot3>http://thegamesdb.net/banners/screenshots/22383-3.jpg</snapshot3>
					<snapshot4>http://thegamesdb.net/banners/screenshots/22383-4.jpg</snapshot4>
					<snapshot5>http://thegamesdb.net/banners/screenshots/22383-5.jpg</snapshot5>
					<snapshot6>http://thegamesdb.net/banners/screenshots/22383-6.jpg</snapshot6>
					<snapshot7>http://thegamesdb.net/banners/screenshots/22383-7.jpg</snapshot7>
					<snapshot8>http://thegamesdb.net/banners/screenshots/22383-8.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/57070-rampage-atari-7800-screenshot-atari-logo.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/57071-rampage-atari-7800-screenshot-title-screen.jpg</snapshot10>
			</game>
			<game name="F-18 Hornet (1988)(Absolute Entertainment)(NTSC)">
					<rom name="F-18_Hornet_1988_Absolute_Entertainment_NTSC/F-18_Hornet_1988_Absolute_Entertainment_NTSC.a78" size="0"/>
					<description>F-18 Hornet (1988)(Absolute Entertainment)(NTSC)</description>
					<snapshot1>https://archive.org/serve/F-18_Hornet_1988_Absolute_Entertainment_NTSC/F-18_Hornet_1988_Absolute_Entertainment_NTSC_screenshot.png</snapshot1>
					<plot>Attention all Naval Aviators! Report to your squadron leaders and prepare for deployment. Your tour of duty will take you around the world on some of the most challenging and dangerous missions of your career. F-18 Hornet is a carrier based adventure. Fast, solid 3-D graphics and responsive instrumentation make for an incredible sensation of flight. Fly missions through a variety of terrain executing aerial combat, emergency supply drops, strafing and bombing runs while battling hostile jets, helicopters and tanks. F-18 Hornet features all of the action of carrier based jets including thrilling aircraft carrier take-offs and landings in smooth 3-D animation.</plot>
					<genre>Flight Simulator</genre>
					<releasedate>01/01/1988</releasedate>
					<nplayers>1</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/21093-1.jpg</boxart1>
					<boxart2>http://thegamesdb.net/banners/boxart/original/back/21093-1.jpg</boxart2>
					<boxart3>http://www.mobygames.com/images/covers/l/295648-f-18-hornet-atari-7800-media.jpg</boxart3>
					<snapshot1>http://thegamesdb.net/banners/screenshots/21093-1.jpg</snapshot1>
					<snapshot2>http://thegamesdb.net/banners/screenshots/21093-2.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/72944-f-18-hornet-atari-7800-screenshot-atari-logo.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/72945-f-18-hornet-atari-7800-screenshot-title-screen.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/72946-f-18-hornet-atari-7800-screenshot-mission-overview.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/72947-f-18-hornet-atari-7800-screenshot-beginning-mission-one.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/72948-f-18-hornet-atari-7800-screenshot-airborne.jpg</snapshot7>
					<snapshot8>http://www.mobygames.com/images/shots/l/72949-f-18-hornet-atari-7800-screenshot-enemy-plane-in-sight.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/72950-f-18-hornet-atari-7800-screenshot-taking-off-from-an-aircraft.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/72951-f-18-hornet-atari-7800-screenshot-i-better-shoot-this-enemy.jpg</snapshot10>
			</game>
			<game name="Tomcat - The F-14 Fighter Simulator (1989)(Absolute Entertainment)(NTSC)">
					<rom name="Tomcat_-_The_F-14_Fighter_Simulator_1989_Absolute_Entertainment_NTSC/Tomcat_-_The_F-14_Fighter_Simulator_1989_Absolute_Entertainment_NTSC.a78" size="0"/>
					<description>Tomcat - The F-14 Fighter Simulator (1989)(Absolute Entertainment)(NTSC)</description>
					<snapshot1>https://archive.org/serve/Tomcat_-_The_F-14_Fighter_Simulator_1989_Absolute_Entertainment_NTSC/Tomcat_-_The_F-14_Fighter_Simulator_1989_Absolute_Entertainment_NTSC_screenshot.png</snapshot1>
					<plot>Become a F-14 Naval Aviator undergoing seek and destroy missions while dodging and gunning enemy bogeys in deadly dogfights with your 20mm cannon and air-to-air missiles.

Your cockpit comes with state of the art technology, courtesy of the U.S. Air Force: Display and main computer, Bogey Alert Indicator, G-Force Indicator, Electronic Counter Measures, and a Cannon Overheat Indicator (yes, it can overheat!)...and if your feeling up to it, give the ol'bird a boost to Mach 1.0!

The gameplay like other simulation games consists of taking off, flying, combat and landing. Though most of the gameplay focuses around dogfighting with enemy bogeys (dodging missiles). In addition to that, there are also night-flying missions that add difficulty due to limited vision.

Taking off and landing however, also requires additional skill as your doing it on the USS Enterprise (No relation to Star Trek), not on your standard airstrip. Pay attention to the F.D. officer as your preparing to take off (since he's the boss when it comes to this stuff...and try not to run over him...yet).

Your weaponry consists of a M 61 Machine Gun and 3 different AIM Missiles (AIM 7, 9, 54) each packed with 15 missiles (that's a lot of missiles!).

After each mission you will receive a Mission Rating which is based on your flying skill, number of bogey kill and number of weapons fired.</plot>
					<genre>ActionFlight Simulator</genre>
					<releasedate>01/01/1989</releasedate>
					<nplayers>1</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/22389-1.jpg</boxart1>
					<boxart2>http://thegamesdb.net/banners/boxart/original/back/22389-1.jpg</boxart2>
					<snapshot1>http://thegamesdb.net/banners/screenshots/22389-1.jpg</snapshot1>
					<snapshot2>http://thegamesdb.net/banners/screenshots/22389-2.jpg</snapshot2>
					<snapshot3>http://thegamesdb.net/banners/screenshots/22389-3.jpg</snapshot3>
					<snapshot4>http://thegamesdb.net/banners/screenshots/22389-4.jpg</snapshot4>
					<snapshot5>http://thegamesdb.net/banners/screenshots/22389-5.jpg</snapshot5>
					<snapshot6>http://thegamesdb.net/banners/screenshots/22389-6.jpg</snapshot6>
					<snapshot7>http://thegamesdb.net/banners/screenshots/22389-7.jpg</snapshot7>
					<snapshot8>http://thegamesdb.net/banners/screenshots/22389-8.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/72930-dan-kitchen-s-tomcat-the-f-14-fighter-simulator-atari-7800.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/72931-dan-kitchen-s-tomcat-the-f-14-fighter-simulator-atari-7800.jpg</snapshot10>
			</game>
			<game name="Tank Command (1988)(Froggo)(NTSC)">
					<rom name="Tank_Command_1988_Froggo_NTSC/Tank_Command_1988_Froggo_NTSC.a78" size="0"/>
					<description>Tank Command (1988)(Froggo)(NTSC)</description>
					<snapshot1>https://archive.org/serve/Tank_Command_1988_Froggo_NTSC/Tank_Command_1988_Froggo_NTSC_screenshot.png</snapshot1>
					<plot>Tank Command is a vertically scrolling action game. You control a tank on a mission to capture the enemy flag as well as earn as many points as possible. To do this, you will need to blast your way through their defenses on three levels of increasing difficulty. Blocking your progress are enemy tanks, pillboxes, missiles, jeeps, infantry, huts, and more, all of which earn you points when destroyed. Your tank is equipped with a limited amount of fuel and ammo, however it can be replenished occasionally by collecting the bonus icons when they appear on the screen. If you can make it past all of the obstacles and capture the flag, then you win the game!

The 7800 is pretty much void of super-rare games like the 2600'?s Tooth Protectors and Chase the Chuckwagon, but don't worry, tracking down Tank Command in a box will cost you a pretty penny. As far as gameplay goes, Tank Command is not going to blow anyone away. Here you have a vertical scroller like Commando or Ikari Warriors minus the charm, quality level design, and reasonable difficulty. There are only three levels in the game, but just like its Froggo cousin Water Ski, the difficulty ramps so severely after the mindless first level that continuing takes strong will. The pink terrain is a bit odd, as well. Tank Command was only released in NTSC format.</plot>
					<genre>Action</genre>
					<releasedate>01/01/1988</releasedate>
					<nplayers>1</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/22388-1.jpg</boxart1>
					<boxart2>http://thegamesdb.net/banners/boxart/original/back/22388-1.jpg</boxart2>
					<snapshot1>http://thegamesdb.net/banners/screenshots/22388-1.jpg</snapshot1>
					<snapshot2>http://thegamesdb.net/banners/screenshots/22388-2.jpg</snapshot2>
					<snapshot3>http://thegamesdb.net/banners/screenshots/22388-3.jpg</snapshot3>
					<snapshot4>http://thegamesdb.net/banners/screenshots/22388-4.jpg</snapshot4>
					<snapshot5>http://thegamesdb.net/banners/screenshots/22388-5.jpg</snapshot5>
					<snapshot6>http://thegamesdb.net/banners/screenshots/22388-6.jpg</snapshot6>
					<snapshot7>http://thegamesdb.net/banners/screenshots/22388-7.jpg</snapshot7>
					<snapshot8>http://thegamesdb.net/banners/screenshots/22388-8.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/82782-tank-command-atari-7800-screenshot-atari-logo.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/82783-tank-command-atari-7800-screenshot-title-screen.jpg</snapshot10>
			</game>
			<game name="Food Fight">
					<rom name="Food_Fight_1987_Atari_NTSC/Food_Fight_1987_Atari_NTSC.a78" size="0"/>
					<description>Food Fight</description>
					<snapshot1>https://archive.org/serve/Food_Fight_1987_Atari_NTSC/Food_Fight_1987_Atari_NTSC_screenshot.png</snapshot1>
					<plot>Hurry! Hurry! Step Right Up! Earn Your Just Desserts!

Once there was a fellow named Charley Chuck. More than anything, Charley loved to eat. So when he went to the carnival one hot summer day, he headed straight for the Food Fight contest.</plot>
					<genre>Action</genre>
					<releasedate>01/01/1987</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/21044-1.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/28227-food-fight-atari-7800-front-cover.jpg</boxart2>
					<boxart3>http://thegamesdb.net/banners/boxart/original/back/21044-1.jpg</boxart3>
					<boxart4>http://www.mobygames.com/images/covers/l/28228-food-fight-atari-7800-back-cover.jpg</boxart4>
					<snapshot1>http://www.mobygames.com/images/shots/l/55491-food-fight-atari-7800-screenshot-atari-logo.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/55492-food-fight-atari-7800-screenshot-title-screen.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/55493-food-fight-atari-7800-screenshot-get-ready-to-begin.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/55494-food-fight-atari-7800-screenshot-grab-some-food-to-throw-at.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/55495-food-fight-atari-7800-screenshot-rapid-firing-some-watermelon.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/55496-food-fight-atari-7800-screenshot-eating-an-ice-cream-cone.jpg</snapshot6>
			</game>
			<game name="Baseball (1989)(Absolute Entertainment)(PAL)">
					<rom name="Baseball_1989_Absolute_Entertainment_PAL/Baseball_1989_Absolute_Entertainment_PAL.a78" size="0"/>
					<description>Baseball (1989)(Absolute Entertainment)(PAL)</description>
					<snapshot1>https://archive.org/serve/Baseball_1989_Absolute_Entertainment_PAL/Baseball_1989_Absolute_Entertainment_PAL_screenshot.png</snapshot1>
					<plot>It's the last game of the World Series. You're in the 9th innings. Bases loaded. One out. And your up to bat.

What do you do? Swing away? Wait for a walk? Go for the fences? It's all up to you, just like in real pro ball.

Sure, we'll give you the options. And some tips. Like in pitching. Batting. And Fielding. But, it's you call .

There are 6 full-color, live action screens - just like the ones you see on TV! The pitching/battting screen, left infield, right infield, leftfield, centerfield and rightfield.

So, start warming up. Step up to the plate. And take your best swing at winning
the series!

Originally designed by Alex DeMeo, the 7800 version was programmed by Robert Curtiss.</plot>
					<genre>Sports</genre>
					<releasedate>05/27/1989</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/22379-1.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/35897-basketbrawl-atari-7800-front-cover.jpg</boxart2>
					<boxart3>http://thegamesdb.net/banners/boxart/original/back/22379-1.jpg</boxart3>
					<boxart4>http://www.mobygames.com/images/covers/l/35898-basketbrawl-atari-7800-back-cover.jpg</boxart4>
					<boxart5>http://www.mobygames.com/images/covers/l/35899-basketbrawl-atari-7800-media.jpg</boxart5>
					<snapshot1>http://thegamesdb.net/banners/screenshots/22379-1.jpg</snapshot1>
					<snapshot2>http://thegamesdb.net/banners/screenshots/22379-2.jpg</snapshot2>
					<snapshot3>http://thegamesdb.net/banners/screenshots/22379-3.jpg</snapshot3>
					<snapshot4>http://thegamesdb.net/banners/screenshots/22379-4.jpg</snapshot4>
					<snapshot5>http://thegamesdb.net/banners/screenshots/22379-5.jpg</snapshot5>
					<snapshot6>http://thegamesdb.net/banners/screenshots/22379-6.jpg</snapshot6>
					<snapshot7>http://thegamesdb.net/banners/screenshots/22379-7.jpg</snapshot7>
					<snapshot8>http://thegamesdb.net/banners/screenshots/22379-8.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/56348-basketbrawl-atari-7800-screenshot-atari-logo.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/56349-basketbrawl-atari-7800-screenshot-title-screen.jpg</snapshot10>
			</game>
			<game name="Space War! Rev 20040318 (2004)(Eric Ball)(PD)">
					<rom name="Space_War_Rev_20040318_2004_Eric_Ball_PD/Space_War_Rev_20040318_2004_Eric_Ball_PD.a78" size="0"/>
					<description>Space War! Rev 20040318 (2004)(Eric Ball)(PD)</description>
					<snapshot1>https://archive.org/images/emulation_default.jpg</snapshot1>
					<plot>In a desperate attempt to stop inner-city gang wars, the city leaders organized a basketball league.  The league is scheduled to play on three courts: a street, a junkyard, and a rooftop.  The mayor figured that a friendly game of hoops would be a much more peaceful way to settle disputes. He was wrong.You can choose 1-on-1 or 2-on-2 game modes. There are six characters to choose from (ten in Atari Lynx version); each with their own health, speed, and power attributes. Each player without the ball can jump to block a shot or punch there opponent to get the ball. There's also an option to perform a power throw on an opposing player. Players with the ball can shoot or pass. Power ups appear on the court at random instances. These power up one attribute for the player. For example, the lightning power up increases the player's speed. The referee does not call fouls, but does hurl knives at the players.</plot>
					<genre>Sports</genre>
					<releasedate>1990</releasedate>
					<nplayers>1-2s</nplayers>
					<boxart1>http://www.mobygames.com/images/covers/l/35897-basketbrawl-atari-7800-front-cover.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/35898-basketbrawl-atari-7800-back-cover.jpg</boxart2>
					<boxart3>http://www.mobygames.com/images/covers/l/35899-basketbrawl-atari-7800-media.jpg</boxart3>
					<snapshot1>http://www.mobygames.com/images/shots/l/56348-basketbrawl-atari-7800-screenshot-atari-logo.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/56349-basketbrawl-atari-7800-screenshot-title-screen.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/56350-basketbrawl-atari-7800-screenshot-game-options.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/56351-basketbrawl-atari-7800-screenshot-choose-a-character.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/56352-basketbrawl-atari-7800-screenshot-some-more-game-options.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/56353-basketbrawl-atari-7800-screenshot-a-game-in-progress.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/56354-basketbrawl-atari-7800-screenshot-taking-a-shot.jpg</snapshot7>
			</game>
			<game name="Pete Rose Baseball (1989)(Absolute Entertainment)(NTSC)">
					<rom name="Pete_Rose_Baseball_1989_Absolute_Entertainment_NTSC/Pete_Rose_Baseball_1989_Absolute_Entertainment_NTSC.a78" size="0"/>
					<description>Pete Rose Baseball (1989)(Absolute Entertainment)(NTSC)</description>