<?xml version="1.0" ?>
<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT title_clean (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT perspective (#PCDATA)>
		<!ELEMENT rating (#PCDATA)>
		<!ELEMENT ESRB (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT thegamesdb_id (#PCDATA)>
		<!ELEMENT gamefaqs_url (#PCDATA)>
		<!ELEMENT moby_url (#PCDATA)>
		<!ELEMENT consolegrid_url (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>		
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
<datafile>
	<header>
		<emu_name>Internet Archive Best Of - Sega Genesis</emu_name>
		<emu_parser>NoIntro_parser.xml</emu_parser>
		<emu_description>Top 50 Sega Genesis</emu_description>
		<emu_category>Top 50</emu_category>
		<emu_version>20151219</emu_version>
		<emu_date>12/19/2015</emu_date>
		<emu_author>Zach_Morris</emu_author>
		<emu_homepage>http://www.no-intro.org</emu_homepage>
		<emu_baseurl>http://archive.org/download/</emu_baseurl>
		<emu_launcher>external</emu_launcher>
		<emu_ext_launch_cmd>"%APP_PATH%\retroarch.exe" %NETPLAY_COMMAND% -L "%APP_PATH%\cores\genesis_plus_gx_libretro.dll" "%ROM_PATH%"</emu_ext_launch_cmd>
		<emu_downloadpath>default</emu_downloadpath>
		<emu_postdlaction>unzip_rom</emu_postdlaction>
		<emu_comment>Pardon the pun, but the Sega Genesis/Mega Drive was a game changer. As a 16-bit system, it meant sharper resolution, bigger characters, more complex animations, and digitally sampled audio. The graphics began to approach cartoon-like quality, allowing developers to design large casts of recognizable characters. Released in 1989 with the slogan "Genesis does what Nintendon’t", it was consistently neck and neck with its biggest competitor, the Super Nintendo Entertainment System.[CR]If you missed out on these classics, or just want an old-school nostalgia fest, you can find many of them on the Sonic Ultimate Genesis Collection for Xbox 360 and PS3, or on many downloadable services out there. Now, allow us to present our list of the 50 best Sega Genesis games of all time...</emu_comment>
			<emu_thumb>special://home/addons/plugin.program.iarl/resources/skins/Default/media/Genesis_bestof.jpg</emu_thumb>
			<emu_banner>special://home/addons/plugin.program.iarl/resources/skins/Default/media/Genesis_best_of_banner.jpg</emu_banner>
			<emu_fanart>https://i.ytimg.com/vi/04m05wdZAJk/maxresdefault.jpg</emu_fanart>
			<emu_logo>http://upload.wikimedia.org/wikipedia/en/1/12/GenesisLogo.png</emu_logo>
			<emu_trailer>35jGnZ-e3jc</emu_trailer>
		</header>
			<game name="Sensible Soccer - International Edition (Europe) (En,Fr,De,It)">
				<description>50.  Sensible Soccer - International Edition</description>
				<rom crc="04E3BCCA" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FSensible%20Soccer%20-%20International%20Edition%20%28Europe%29%20%28En%2CFr%2CDe%2CIt%29.zip" sha1="B88833BA92E084D4433E2B22EEB67E71ED36CD5C" size="224502" />
				<title_clean>Sensible Soccer - International Edition</title_clean>
				<plot>Before FIFA debuted on in late 1993, Sensi (as it’s known by acolytes) was the ruling king of console football--and even after EA’s tour de force, there were many who preferred this more cosmetically modest offering. Presenting a top-down view reminiscent of computer soccer titles like Imagineer’s Kick Off line, developer Sensible Software was open about forgoing flashy graphics in favor of 60fps movement and a persistent wide-angle perspective allowing for full-team tactical play.[CR]Some versions included licensed teams, but all allow the player to input their own team and player names. It's something pretty much every sports game does these days, but there's still something special about seeing you and your mates running around the screen, representing Crapston Utd.</plot>
				<releasedate>31/12/1994</releasedate>
				<year>1994</year>
				<genre>Sports</genre>
				<nplayers>1-2 Alt</nplayers>
				<thegamesdb_id>20450</thegamesdb_id>
				<giantbomb_url>http://www.giantbomb.com/international-sensible-soccer/3030-16250/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/4785</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/20450-1.jpg</boxart1>
				<banner1>http://i.imgur.com/f0EuHio.jpg</banner1>
			</game>
			<game name="Skitchin' (USA, Europe)">
				<description>49.  Skitchin'</description>
				<rom crc="F785F9D7" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FSkitchin%27%20%28USA%2C%20Europe%29.zip" sha1="98BE93964C14EBC91727B429DD7A7A563B4E2E9F" size="1012860" />
				<title_clean>Skitchin'</title_clean>
				<plot>There are games you play for their evergreen appeal, and there are the ones you dig back up as time capsules of the era in which they were unleashed upon the world. It's the latter case with Skitchin’, a radical blitz of x-treme 1990s ‘tude with a color palette so downright tubular you’ll need wraparound shades just to get past the title screen.[CR]Srsly tho (as we say back here in the 21st century), this one-of-a-kind rollerblade racer can’t be faulted for originality, nor for the challenge of racing down American freeways by slingshotting between the bumpers of hostile motorists, flannel shirts all a-billow. With a graded trick system, hidden warp boards and the 16-bit console's best attempt at a grunge soundtrack, Skitchin is worth your attention, even now.</plot>
				<releasedate>23/12/1994</releasedate>
				<year>1994</year>
				<genre>Driving, Racing, Sports</genre>
				<studio>Electronic Arts, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>4.5</rating>
				<ESRB>T - Teen</ESRB>
				<videoid>gaTQ2b9Wypc</videoid>
				<thegamesdb_id>4618</thegamesdb_id>
				<gamefaqs_url>http://www.gamefaqs.com/genesis/586462-skitchin</gamefaqs_url>
				<mobygames_url>http://www.mobygames.com/game/genesis/skitchin</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/skitchin/3030-18512/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/4803</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/4618-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/4618-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/39166-skitchin-genesis-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/74992-skitchin-genesis-media.jpg</boxart4>
				<snapshot1>http://www.mobygames.com/images/shots/l/138874-skitchin-genesis-screenshot-all-those-warnings-just-made-me.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/138867-skitchin-genesis-screenshot-title-screen.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/138868-skitchin-genesis-screenshot-main-menu.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/138869-skitchin-genesis-screenshot-the-shop.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/138870-skitchin-genesis-screenshot-pre-race-introduction.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/138871-skitchin-genesis-screenshot-game-start.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/138872-skitchin-genesis-screenshot-ouch-dudes.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/138873-skitchin-genesis-screenshot-building-up-some-speed.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/138866-skitchin-genesis-screenshot-big-jump.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/138876-skitchin-genesis-screenshot-the-camera-pans-away-as-i-ve-had.jpg</snapshot10>
				<banner1>http://i.imgur.com/0dGuC8Z.png</banner1>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/4618.png</clearlogo1>
			</game>
			<game name="General Chaos (USA, Europe)">
				<description>48.  General Chaos</description>
				<rom crc="F1ECC4DF" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FGeneral%20Chaos%20%28USA%2C%20Europe%29.zip" sha1="AEA1DFA67B0E583A3D367A67499948998CB92F56" size="510979" />
				<title_clean>General Chaos</title_clean>
				<plot>Future Medal of Honor stablemasters Electronic Arts were making forays into the fog of war long before Saving Private Ryan rendered senseless battlefield violence all respectable-like. Shot through with the sly anarchy that marked many a ‘90s console blockbuster, General Chaos is satire so thick you could cut it with a knife--or shoot it, blow it up, stab it with a bayonet, whatevs.[CR]General Chaos and his arch-rival, General Havoc, engage in a series of territorial skirmishes that play like a cross between a PC-based point-and-click and a heavy-artillery version of sports titles such as EA’s NHL series. Multitap-enabled four-way play lets the whole neighborhood get in on the slaughterisin’ fun. For added fun, lob a grenade at your mate, pause the game and watch as the pause state doesn't affect the grenade. Priceless.</plot>
				<releasedate>13/1/1994</releasedate>
				<year>1994</year>
				<genre>Action, Strategy</genre>
				<studio>Electronic Arts, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>Isometric</perspective>
				<rating>4.3</rating>
				<videoid>MIh4pwAjPYg</videoid>
				<thegamesdb_id>1939</thegamesdb_id>
				<gamefaqs_url>http://www.gamefaqs.com/genesis/586206-general-chaos</gamefaqs_url>
				<mobygames_url>http://www.mobygames.com/game/genesis/general-chaos</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/general-chaos/3030-2267/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/4484</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/1939-1.jpg</boxart1>
				<boxart2>http://i.imgur.com/tv2vfkT.png</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/98302-general-chaos-genesis-media.jpg</boxart3>
				<snapshot1>http://www.mobygames.com/images/shots/l/182445-general-chaos-genesis-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/182446-general-chaos-genesis-screenshot-main-menu.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/182447-general-chaos-genesis-screenshot-boot-camp-gives-a-basic-insight.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/182449-general-chaos-genesis-screenshot-general-chaos.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/182451-general-chaos-genesis-screenshot-choosing-where-to-strike.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/182450-general-chaos-genesis-screenshot-close-combat-battle.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/182452-general-chaos-genesis-screenshot-battle-heating-up.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/182453-general-chaos-genesis-screenshot-two-commando-teams-fighting.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/182454-general-chaos-genesis-screenshot-the-score-increases-the-number.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/182455-general-chaos-genesis-screenshot-choosing-a-squad-you-can.jpg</snapshot10>
				<banner1>http://i.imgur.com/aosZdw7.png</banner1>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/1939.png</clearlogo1>
			</game>
			<game name="Bonanza Bros. (World) (Rev B)">
				<description>47.  Bonanza Bros.</description>
				<rom crc="20D1AD4C" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FBonanza%20Bros.%20%28World%29%20%28Rev%20B%29.zip" sha1="31C589BC0D1605502CDD04069DC4877811E84E58" size="204245" />
				<title_clean>Bonanza Bros.</title_clean>
				<plot>Robo and Mobo Bonanza are 3D-rendered masters of infiltration whose innocent television-watching is suddenly interrupted by a shadowy deus ex machina offering some cockamamie rationale for why it’s entirely reasonable to go on a roaring rampage of trespass, theft, and petty larceny. Oh, the lengths to which western publishers would go to establish that their games weren’t about criminality![CR]Thus the stage is set for an exploration-heavy, stealth-centric series of heists whose gameplay would go on to underpin the likes of Metal Gear Solid. Persistent split-screen means two players can team up for shared bouts of treasure-stealing, guard-tranquilizing fun.</plot>
				<releasedate>23/12/1991</releasedate>
				<year>1991</year>
				<genre>Action</genre>
				<studio>SEGA of America, Inc.</studio>
				<nplayers>1-2 Sim</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.1</rating>
				<videoid>EX9qBRJIOes</videoid>
				<thegamesdb_id>4290</thegamesdb_id>
				<gamefaqs_url>http://www.gamefaqs.com/genesis/586069-bonanza-bros</gamefaqs_url>
				<mobygames_url>http://www.mobygames.com/game/genesis/bonanza-bros</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/bonanza-bros/3030-14087/</giantbomb_url>
				<boxart1>http://img.gamefaqs.net/box/4/5/8/27458_front.jpg</boxart1>
				<boxart2>http://www.mobygames.com/images/covers/l/246249-bonanza-bros-genesis-back-cover.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/162898-bonanza-bros-genesis-media.jpg</boxart3>
				<snapshot1>http://www.mobygames.com/images/shots/l/64350-bonanza-bros-genesis-screenshot-title.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/64351-bonanza-bros-genesis-screenshot-introduction-sequence.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/64352-bonanza-bros-genesis-screenshot-yeah-right.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/64353-bonanza-bros-genesis-screenshot-stage-1-company.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/64354-bonanza-bros-genesis-screenshot-got-all-the-treasures-and-am.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/64355-bonanza-bros-genesis-screenshot-robo-makes-a-quick-getaway.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/64356-bonanza-bros-genesis-screenshot-stage-2-millionaire-s-mansion.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/64357-bonanza-bros-genesis-screenshot-watch-where-you-re-going-robo.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/64358-bonanza-bros-genesis-screenshot-a-guard-gets-squashed-by-an.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/64359-bonanza-bros-genesis-screenshot-about-to-run-out-of-time.jpg</snapshot10>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/4290.png</clearlogo1>
			</game>
			<game name="Mega-Lo-Mania (Europe)">
				<description>46.  Mega-Lo-Mania</description>
				<rom crc="2148D56D" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FMega-Lo-Mania%20%28Europe%29.zip" sha1="E861551EDABE55181ED1B7260169E953AF903B5E" size="552180" />
				<title_clean>Mega-Lo-Mania</title_clean>
				<plot>Tyrants: Fight Through Time (Mega-Lo-Mania in Europe) is Sensible Software’s take on the god game genre pioneered by the likes of Peter Molyneux’s Populous. Released the same year as Sid Meier’s Civilization, the title places a stronger emphasis on combat and martial supremacy.[CR]Making it from the dawn of time all the way through to the distant future of 2001 will require strategic resource-management skills, a watchful eye on the research tree, and the bloodthirsty will to slaughter unfortunate humans born into any civilization that worships a rival god. The game usually ends with someone developing and launching nuclear weapons, at which point amazing speech synthesis declares camply 'we've been nuked!'.</plot>
				<releasedate>23/12/1992</releasedate>
				<year>1992</year>
				<genre>Strategy</genre>
				<studio>Virgin Games, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>Top-Down</perspective>
				<rating>3.3</rating>
				<videoid>W7WG997w01M</videoid>
				<thegamesdb_id>18844</thegamesdb_id>
				<gamefaqs_url>http://www.gamefaqs.com/genesis/586569-tyrants</gamefaqs_url>
				<mobygames_url>http://www.mobygames.com/game/genesis/mega-lo-mania</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/18844-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/18844-1.png</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/98404-mega-lo-mania-genesis-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/98913-mega-lo-mania-genesis-media.jpg</boxart4>
				<snapshot1>http://www.mobygames.com/images/shots/l/98186-mega-lo-mania-genesis-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/224865-mega-lo-mania-genesis-screenshot-title-screen-us-version.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/98187-mega-lo-mania-genesis-screenshot-player-select.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/98188-mega-lo-mania-genesis-screenshot-intro.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/98189-mega-lo-mania-genesis-screenshot-choosing-an-island.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/98190-mega-lo-mania-genesis-screenshot-a-brown-island.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/98191-mega-lo-mania-genesis-screenshot-a-white-island.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/159991-mega-lo-mania-genesis-screenshot-the-japanese-version-has.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/159992-mega-lo-mania-genesis-screenshot-cri-have-also-redrawn-the.jpg</snapshot9>
				<snapshot10>http://img.gamefaqs.net/screens/8/1/0/gfs_62760_1_1.jpg</snapshot10>
			</game>
			<game name="Jimmy White's Whirlwind Snooker (Europe)">
				<description>45.  Jimmy White's Whirlwind Snooker</description>
				<rom crc="0AEF5B1F" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FJimmy%20White%27s%20Whirlwind%20Snooker%20%28Europe%29.zip" sha1="040C810CCBE6310D369AA147471213D898EC2AD5" size="220305" />
				<title_clean>Jimmy White's Whirlwind Snooker</title_clean>
				<plot>Archer MacLean--the 8-bit rockstar programmer responsible for the likes of Dropzone and International Karate +--was the mastermind behind this unprecedentedly realistic simulation of the second-best thing to do in an English pub. Players raised to believe that the Genesis was incapable of sophisticated 3D graphics must have pinched themselves at the sight of this fast-flowing, full-screen sim which mixes realistic physics with MacLean’s trademark brand of offbeat humor.[CR]Full games of snooker can be broken up by a showboating Trick Shot mode, mastery of which might just save you from having to buy the next round (but probably not).</plot>
				<releasedate>23/12/1994</releasedate>
				<year>1994</year>
				<genre>Sports</genre>
				<nplayers>1-2 VS</nplayers>
				<perspective>1st-Person</perspective>
				<rating>3.0</rating>
				<videoid>yTOoUwIPw_g</videoid>
				<thegamesdb_id>20393</thegamesdb_id>
				<gamefaqs_url>http://www.gamefaqs.com/genesis/941827-jimmy-whites-whirlwind-snooker</gamefaqs_url>
				<mobygames_url>http://www.mobygames.com/game/genesis/jimmy-whites-whirlwind-snooker</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/jimmy-whites-whirlwind-snooker/3030-2371/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/4544</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/20393-1.jpg</boxart1>
				<boxart2>http://www.mobygames.com/images/covers/l/17688-jimmy-white-s-whirlwind-snooker-genesis-back-cover.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/17689-jimmy-white-s-whirlwind-snooker-genesis-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/153883-jimmy-white-s-whirlwind-snooker-genesis-media.jpg</boxart4>
				<snapshot1>http://www.mobygames.com/images/shots/l/102766-jimmy-white-s-whirlwind-snooker-genesis-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/102767-jimmy-white-s-whirlwind-snooker-genesis-screenshot-ingame.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/102768-jimmy-white-s-whirlwind-snooker-genesis-screenshot-ingame.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/102771-jimmy-white-s-whirlwind-snooker-genesis-screenshot-ingame.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/102772-jimmy-white-s-whirlwind-snooker-genesis-screenshot-ingame.jpg</snapshot5>
				<snapshot6>http://static.giantbomb.com/uploads/scale_large/0/1987/1124296-jimmy_whites_whirlwind_snooker_3.gif</snapshot6>
				<snapshot7>http://static.giantbomb.com/uploads/scale_large/0/1987/1124295-jimmy_whites_whirlwind_snooker_2.gif</snapshot7>
				<snapshot8>http://static.giantbomb.com/uploads/scale_large/0/1987/1124294-jimmy_whites_whirlwind_snooker_1.gif</snapshot8>
				<snapshot9>http://static.giantbomb.com/uploads/scale_large/0/1987/1124293-jimmy_whites_whirlwind_snooker.gif</snapshot9>
				<snapshot10>http://static.giantbomb.com/uploads/scale_large/0/987/226647-jwws_amiga_taunt.png</snapshot10>
			</game>
			<game name="Ghouls'n Ghosts (USA, Europe)">
				<description>44.  Ghouls'n Ghosts</description>
				<rom crc="D31BD910" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FGhouls%27n%20Ghosts%20%28USA%2C%20Europe%29.zip" sha1="3A3E9EB5CAAF6CFB75E99ED2843D58B3DDA7284F" size="442389" />
				<title_clean>Ghouls'n Ghosts</title_clean>
				<plot>The sequel to Ghosts 'n' Goblins once again casts you as the knight Arthur, off to rescue the soul of his beloved Princess Prin Prin. Taking damage strips you of your armor, making you fight monsters in your underwear, just like in real life.[CR]With its spooky setting and infamous difficulty (which often sees you trying to survive while transformed into a baby), you could call Ghouls 'n' Ghosts the Dark Souls of its day. As if to prove its brutal, unforgiving nature, you have to beat it twice in a row just to get a proper ending!</plot>
				<releasedate>23/12/1989</releasedate>
				<year>1989</year>
				<genre>Action</genre>
				<studio>SEGA of America, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.9</rating>
				<videoid>QGjCyICTcP4</videoid>
				<thegamesdb_id>2592</thegamesdb_id>
				<gamefaqs_url>http://www.gamefaqs.com/genesis/563325-ghouls-n-ghosts</gamefaqs_url>
				<mobygames_url>http://www.mobygames.com/game/genesis/ghouls-n-ghosts</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/ghouls-n-ghosts/3030-12381/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/4489</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/2592-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/2592-1.jpg</boxart2>
				<boxart3>http://i.imgur.com/A6WzNs6.jpg</boxart3>
				<boxart4>http://i.imgur.com/14Xexv6.jpg</boxart4>
				<boxart5>http://i.imgur.com/ycLrscp.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/74622-ghouls-n-ghosts-genesis-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/189614-ghouls-n-ghosts-genesis-media.jpg</boxart7>
				<boxart8>http://www.mobygames.com/images/covers/l/117626-ghouls-n-ghosts-genesis-media.jpg</boxart8>
				<snapshot1>http://www.mobygames.com/images/shots/l/93081-ghouls-n-ghosts-genesis-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/522770-ghouls-n-ghosts-genesis-screenshot-japanese-title-screen.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/93082-ghouls-n-ghosts-genesis-screenshot-the-game-map.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/93083-ghouls-n-ghosts-genesis-screenshot-ready-to-save-the-world.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/93084-ghouls-n-ghosts-genesis-screenshot-nice-little-birdie.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/93085-ghouls-n-ghosts-genesis-screenshot-what-hero-is-complete-without.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/93086-ghouls-n-ghosts-genesis-screenshot-an-early-grave.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/93087-ghouls-n-ghosts-genesis-screenshot-watch-those-skull-breathers.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/93088-ghouls-n-ghosts-genesis-screenshot-a-close-call.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/93089-ghouls-n-ghosts-genesis-screenshot-birdies-everywhere.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/2592-1.jpg</fanart1>
				<banner1>http://i.imgur.com/B9amNCZ.jpg</banner1>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/2592.png</clearlogo1>
			</game>
			<game name="Comix Zone (USA)">
				<description>43.  Comix Zone (USA)</description>
				<rom crc="17DA0354" name="No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2FComix%20Zone%20%28USA%29.zip" sha1="E8747EEFDF61172BE9DA8787BA5BE447EC73180F" size="1618766" />
				<title_clean>Comix Zone</title_clean>