<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT emu_command (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
	<datafile>
		<header>
			<emu_name>MSX</emu_name>
			<emu_parser>NoIntro_parser.xml</emu_parser>
			<emu_description>MSX</emu_description>
			<emu_category>PC</emu_category>
			<emu_version>092816</emu_version>
			<emu_date>09/28/2016</emu_date>
			<emu_author>Zach Morris</emu_author>
			<emu_homepage>http://www.no-intro.org</emu_homepage>
			<emu_baseurl>https://archive.org/download/MESS_0.151_Software_List_ROMs/</emu_baseurl>
			<emu_launcher>external</emu_launcher>
			<emu_ext_launch_cmd>"%APP_PATH%\retroarch.exe" %NETPLAY_COMMAND% -L "%APP_PATH%\cores\bluemsx_libretro.dll" "%ROM_PATH%"</emu_ext_launch_cmd>
			<emu_downloadpath>default</emu_downloadpath>
			<emu_postdlaction>none</emu_postdlaction>
			<emu_comment>Internet Archive MSX List by Zach Morris.

MSX is the name of a standardized home computer architecture, first announced by Microsoft in 1983. It was conceived by Kazuhiko Nishi, then Vice-president at Microsoft Japan and Director at ASCII Corporation. It is said that Microsoft led the project as an attempt to create unified standards among hardware makers.

Developer:  Microsoft</emu_comment>
			<emu_thumb>special://home/addons/plugin.program.iarl/resources/skins/Default/media/4929-1.jpg</emu_thumb>
			<emu_banner>http://i.imgur.com/1B0GXoQ.jpg</emu_banner>
			<emu_fanart>https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Canon_V-20_MSX_computer.jpg/1280px-Canon_V-20_MSX_computer.jpg</emu_fanart>
			<emu_logo>https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/MSX-Logo.svg/200px-MSX-Logo.svg.png</emu_logo>
			<emu_trailer>5RLDGc4Pmhc</emu_trailer>
		</header>
			<game name="10-Yard Fight (Jpn)">
					<description>10-Yard Fight (Jpn)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F10yard.zip" size="14232"/>
					<releasedate>01/01/1986</releasedate>
					<studio>Irem</studio>
					<plot>You're the quarterback in this amazingly real football game! Enjoy realistic gridiron action as you move your team up and down the field to victory! Run, pass, kick, punt... you call the plays in this true-to-life football game. Play against the computer or against a friend for hours of real football action. The sights, the sounds and the plays are so real you'll think you're right on the fifty yard line!</plot>
					<genre>Sports</genre>
					<releasedate>1986</releasedate>
					<nplayers>1-2s</nplayers>
					<boxart1>http://img.gamefaqs.net/box/9/9/7/22997_front.jpg</boxart1>
					<snapshot1>http://img.gamefaqs.net/screens/3/7/7/gfs_78403_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/9/e/a/gfs_78403_2_1.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/129084-10-yard-fight-msx-screenshot-title-screen.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/129085-10-yard-fight-msx-screenshot-beginning-a-play.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/129086-10-yard-fight-msx-screenshot-tackled.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/129087-10-yard-fight-msx-screenshot-near-the-end-zone.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/129088-10-yard-fight-msx-screenshot-uh-no-pass-interception.jpg</snapshot7>
			</game>
			<game name="123 (Arab)">
					<description>123 (Arab)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F123.zip" size="18197"/>
					<releasedate>01/01/1986</releasedate>
					<studio>Al Alamiah</studio>
					<plot>The main idea of this game is that players take control of a football team and have the task of trying to score a touchdown before the clock runs out.Players start out as a high school team. Games consists of two halves. One touchdown must be scored before time runs out in each half or the game is lost. After a touchdown is scored, the half ends and the 2nd half of the game starts. If the player scores in both halves, they win the game, and then move on to the next level of difficulty. Difficulty levels after high school go from college, pro, then to super. The higher the difficulty, the less amount of time is given for a player to score a touchdown.Since the game is concerned with scoring touchdowns, in the 1 player game the player is always on offense. Players can score points for completing passes and for gaining yards by either rushing or passing. Scoring a touchdown also adds to the players score, as does any remaining time on the clock after the touchdown is scored. Also after a touchdown, the player can add on to their score by kicking an extra point. Other rules on the field include getting a 1st down to add time to the clock. If the player throws an interception or go four downs without getting a 1st down, they are penalized yards.In a 2 player game, the second player plays defense until it's their turn to play offense.</plot>
					<genre>Sports</genre>
					<releasedate>1986</releasedate>
					<nplayers>1-2s</nplayers>
					<snapshot1>http://www.mobygames.com/images/shots/l/129084-10-yard-fight-msx-screenshot-title-screen.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/129085-10-yard-fight-msx-screenshot-beginning-a-play.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/129086-10-yard-fight-msx-screenshot-tackled.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/129087-10-yard-fight-msx-screenshot-near-the-end-zone.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/129088-10-yard-fight-msx-screenshot-uh-no-pass-interception.jpg</snapshot5>
			</game>
			<game name="1942 (Jpn)">
					<description>1942 (Jpn)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F1942.zip" size="32756"/>
					<releasedate>01/01/1986</releasedate>
					<studio>ASCII</studio>
					<plot>1942... you and daring fighter pilot &quot;Super Ace&quot; are engaged in realistic, thrilling and challenging high-flying battles with the enemy. Over land, on the sea and in the air, your own skill and dexterity... combined with Super Ace's flying mastery, duel enemy pilots in fighter and bomber craft. 1942... it's airplanes taking off and landing on ocean-going aircraft carriers... disrupting enemy formations ready to attack... intercepting enemy air-warriors you must defeat by &quot;blasting 'em out of the sky.&quot; Will it be victory? Or defeat? It's in your skillful hands!</plot>
					<genre>Action</genre>
					<releasedate>1986</releasedate>
					<nplayers>1-2s</nplayers>
					<videoid>dXarj-ZWvXM</videoid>
					<boxart1>http://img.gamefaqs.net/box/3/4/9/10349_front.jpg</boxart1>
					<snapshot1>http://img.gamefaqs.net/screens/d/c/4/gfs_25365_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/7/5/9/gfs_25365_2_1.jpg</snapshot2>
					<snapshot3>http://img.gamefaqs.net/screens/d/8/9/gfs_25365_2_2.jpg</snapshot3>
					<snapshot4>http://img.gamefaqs.net/screens/4/3/9/gfs_25365_2_3.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/129996-1942-msx-screenshot-title-screen.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/129997-1942-msx-screenshot-leave-the-flight-deck.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/129998-1942-msx-screenshot-shoot-the-big-plane-for-a-bonus.jpg</snapshot7>
					<snapshot8>http://www.mobygames.com/images/shots/l/129999-1942-msx-screenshot-shot-down.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/145732-1942-msx-screenshot-msx1-title-screen.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/145733-1942-msx-screenshot-msx1-taking-off.jpg</snapshot10>
			</game>
			

			
			<game name="1942 (Kor)">
					<description>1942 (Kor)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F1942k.zip" size="32742"/>
					<releasedate>01/01/1987</releasedate>
					<studio>Zemina</studio>
					<plot>1942... you and daring fighter pilot &quot;Super Ace&quot; are engaged in realistic, thrilling and challenging high-flying battles with the enemy. Over land, on the sea and in the air, your own skill and dexterity... combined with Super Ace's flying mastery, duel enemy pilots in fighter and bomber craft. 1942... it's airplanes taking off and landing on ocean-going aircraft carriers... disrupting enemy formations ready to attack... intercepting enemy air-warriors you must defeat by &quot;blasting 'em out of the sky.&quot; Will it be victory? Or defeat? It's in your skillful hands!</plot>
					<genre>Action</genre>
					<releasedate>1986</releasedate>
					<nplayers>1-2s</nplayers>
					<videoid>dXarj-ZWvXM</videoid>
					<boxart1>http://img.gamefaqs.net/box/3/4/9/10349_front.jpg</boxart1>
					<snapshot1>http://img.gamefaqs.net/screens/d/c/4/gfs_25365_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/7/5/9/gfs_25365_2_1.jpg</snapshot2>
					<snapshot3>http://img.gamefaqs.net/screens/d/8/9/gfs_25365_2_2.jpg</snapshot3>
					<snapshot4>http://img.gamefaqs.net/screens/4/3/9/gfs_25365_2_3.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/129996-1942-msx-screenshot-title-screen.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/129997-1942-msx-screenshot-leave-the-flight-deck.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/129998-1942-msx-screenshot-shoot-the-big-plane-for-a-bonus.jpg</snapshot7>
					<snapshot8>http://www.mobygames.com/images/shots/l/129999-1942-msx-screenshot-shot-down.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/145732-1942-msx-screenshot-msx1-title-screen.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/145733-1942-msx-screenshot-msx1-taking-off.jpg</snapshot10>
			</game>
			<game name="Double Face (Arab)">
					<description>Double Face (Arab)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F2facea.zip" size="20335"/>
					<releasedate>01/01/1987</releasedate>
					<studio>Al Alamiah</studio>
					<plot>Set in a post-apocalyptic New York, Double Dragon is the story of Billy and Jimmy Lee, twin brothers trained in the fighting style of Sou-Setsu-Ken. Together, they manage a small martial arts training school, teaching their students in self-defense. One day, Billy's girlfriend, Marian, is kidnapped off the street by the &amp;quot;Black Warriors&amp;quot;, a savage street gang led by a man named Willy. The Black Warriors demand the Lee brothers disclose their martial arts secrets in exchange for Marian's freedom. The Lee brothers set out on a rescue mission to crush the Black Warriors and save Marian.Using whatever techniques they have at their disposal, from the basic punches and kicks to the invulnerable elbow strike, as well any weapon that comes into their hands, the Lee brothers must pursue the gang through the city slum, industrial area and the forest before reaching their hideout to confront the big boss, Willy.The NES version of this game also has an additional VS. fighting mode for one or two players. Players choose from a field of six different characters (Billy and 5 of the enemy characters) and enter into a one-on-one fighting match. Players have to punch, kick, jumpkick, and even use a weapon against their opponents until someone's health bar is fully drained. The winner is the last one standing.</plot>
					<genre>Action</genre>
					<releasedate>1990</releasedate>
					<nplayers>1</nplayers>
					<snapshot1>http://www.mobygames.com/images/shots/l/131658-double-dragon-msx-screenshot-title-screen.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/131659-double-dragon-msx-screenshot-surrounded.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/131660-double-dragon-msx-screenshot-attack-before-you-re-closed-in.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/131661-double-dragon-msx-screenshot-if-you-ve-defeated-these-guys.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/131662-double-dragon-msx-screenshot-level-2-start.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/131663-double-dragon-msx-screenshot-beat-up-the-green-monster.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/131664-double-dragon-msx-screenshot-second-title.jpg</snapshot7>
			</game>
			<game name="Double Jaw (Arab)">
					<description>Double Jaw (Arab)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F2jaw.zip" size="20609"/>
					<releasedate>01/01/1985</releasedate>
					<studio>Al Alamiah</studio>
					<plot>Set in a post-apocalyptic New York, Double Dragon is the story of Billy and Jimmy Lee, twin brothers trained in the fighting style of Sou-Setsu-Ken. Together, they manage a small martial arts training school, teaching their students in self-defense. One day, Billy's girlfriend, Marian, is kidnapped off the street by the &amp;quot;Black Warriors&amp;quot;, a savage street gang led by a man named Willy. The Black Warriors demand the Lee brothers disclose their martial arts secrets in exchange for Marian's freedom. The Lee brothers set out on a rescue mission to crush the Black Warriors and save Marian.Using whatever techniques they have at their disposal, from the basic punches and kicks to the invulnerable elbow strike, as well any weapon that comes into their hands, the Lee brothers must pursue the gang through the city slum, industrial area and the forest before reaching their hideout to confront the big boss, Willy.The NES version of this game also has an additional VS. fighting mode for one or two players. Players choose from a field of six different characters (Billy and 5 of the enemy characters) and enter into a one-on-one fighting match. Players have to punch, kick, jumpkick, and even use a weapon against their opponents until someone's health bar is fully drained. The winner is the last one standing.</plot>
					<genre>Action</genre>
					<releasedate>1990</releasedate>
					<nplayers>1</nplayers>
					<snapshot1>http://www.mobygames.com/images/shots/l/131658-double-dragon-msx-screenshot-title-screen.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/131659-double-dragon-msx-screenshot-surrounded.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/131660-double-dragon-msx-screenshot-attack-before-you-re-closed-in.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/131661-double-dragon-msx-screenshot-if-you-ve-defeated-these-guys.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/131662-double-dragon-msx-screenshot-level-2-start.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/131663-double-dragon-msx-screenshot-beat-up-the-green-monster.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/131664-double-dragon-msx-screenshot-second-title.jpg</snapshot7>
			</game>
			

			
			<game name="3D Golf Simulation (Jpn)">
					<description>3D Golf Simulation (Jpn)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F3dgolf.zip" size="8320"/>
					<releasedate>01/01/1984</releasedate>
					<studio>T&amp;E Soft</studio>
					<plot>3D Golf Simulation is a Sports game, published by T&amp;E Soft,  which was released in Japan in 1983.</plot>
					<genre>Sports</genre>
					<releasedate>1983</releasedate>
					<nplayers>1</nplayers>
					<boxart1>http://img.gamefaqs.net/box/4/9/1/56491_front.jpg</boxart1>
					<snapshot1>http://img.gamefaqs.net/screens/b/0/7/gfs_25691_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/1/9/a/gfs_25691_2_1.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/597545-737-flight-simulator-msx-screenshot-737-fligth-sic-simulator.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/597546-737-flight-simulator-msx-screenshot-title-screen-they-still.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/597547-737-flight-simulator-msx-screenshot-main-menu.jpg</snapshot5>
			</game>
			

			
			<game name="3-D Golf Simulation - High Speed (Jpn)">
					<description>3-D Golf Simulation - High Speed (Jpn)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F3dgolfhs.zip" size="9144"/>
					<releasedate>01/01/1984</releasedate>
					<studio>T&amp;E Soft</studio>
					<plot>3D Golf Simulation is a Sports game, published by T&amp;E Soft,  which was released in Japan in 1983.</plot>
					<genre>Sports</genre>
					<releasedate>1983</releasedate>
					<nplayers>1</nplayers>
					<boxart1>http://img.gamefaqs.net/box/4/9/1/56491_front.jpg</boxart1>
					<snapshot1>http://img.gamefaqs.net/screens/b/0/7/gfs_25691_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/1/9/a/gfs_25691_2_1.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/597545-737-flight-simulator-msx-screenshot-737-fligth-sic-simulator.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/597546-737-flight-simulator-msx-screenshot-title-screen-they-still.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/597547-737-flight-simulator-msx-screenshot-main-menu.jpg</snapshot5>
			</game>
			<game name="The Three Dragon Story (Kor)">
					<description>The Three Dragon Story (Kor)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F3dragon.zip" size="23449"/>
					<releasedate>01/01/1989</releasedate>
					<studio>Zemina</studio>
					<plot>Chan Ka-Kui is Hong Kong's supercop, and he is going after the evil underground gang to take them down once and for all.</plot>
					<genre>Action</genre>
					<releasedate>05/03/1986</releasedate>
					<nplayers>1</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/27032-1.jpg</boxart1>
			</game>
			<game name="3D Tennis (Jpn)">
					<description>3D Tennis (Jpn)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2F3dtennis.zip" size="8643"/>
					<releasedate>01/01/1983</releasedate>
					<studio>ASCII</studio>
					<plot>3D Tennis is a Sports game, published by ASCII Entertainment,  which was released in Japan in 1983.</plot>
					<genre>Sports</genre>
					<releasedate>1983</releasedate>
					<boxart1>http://img.gamefaqs.net/box/4/9/2/56492_front.jpg</boxart1>
					<snapshot1>http://img.gamefaqs.net/screens/2/7/9/gfs_25617_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/8/e/4/gfs_25617_2_1.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/133136-real-tennis-msx-screenshot-title-screen.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/133137-real-tennis-msx-screenshot-bring-it-on.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/133138-real-tennis-msx-screenshot-i-m-not-gonna-make-that-ball.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/133139-real-tennis-msx-screenshot-that-ball-was-in.jpg</snapshot6>
			</game>
			<game name="A1 Spirit - The Way to Formula-1 (Jpn)">
					<description>A1 Spirit - The Way to Formula-1 (Jpn)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2Fa1spirit.zip" size="87625"/>
					<releasedate>01/01/1987</releasedate>
					<studio>Panasoft</studio>
					<plot>F-1 Spirit: The Way To Formula-1 is a top down Formula One Racing game, developed and published by Konami, which was released for the MSX in Japan and Europe in 1987. The game engine is very similar to Konami's Road Fighter. It also features Konami's custom sound chip called Konami SCC (a five-channel chip that compliments the three-channel PSG chip of the MSX computer system, or in other words, a sound custom chip that brings five voices more to the three voices of the PSG sound chip on the system), and great MSX1 graphics to go with it. It was one of the first ROM on MSX with this sound feature. Together with its &quot;3D&quot; spinoff (F-1 Spirit: 3D Special), F-1 Spirit: The Way To Formula-1 was the most extended racing game Konami released for the MSX.</plot>
					<genre>Racing</genre>
					<releasedate>01/01/1987</releasedate>
					<nplayers>2</nplayers>
					<boxart1>http://thegamesdb.net/banners/boxart/original/front/29043-1.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/80194-f-1-spirit-the-road-to-formula-1-msx-front-cover.jpg</boxart2>
					<boxart3>http://www.mobygames.com/images/covers/l/80195-f-1-spirit-the-road-to-formula-1-msx-back-cover.jpg</boxart3>
					<snapshot1>http://img.gamefaqs.net/screens/1/4/e/gfs_155432_1_1.jpg</snapshot1>
					<snapshot2>http://img.gamefaqs.net/screens/b/9/e/gfs_155432_1_2.jpg</snapshot2>
					<snapshot3>http://img.gamefaqs.net/screens/2/2/e/gfs_155432_1_3.jpg</snapshot3>
					<snapshot4>http://img.gamefaqs.net/screens/e/3/e/gfs_155432_1_4.jpg</snapshot4>
					<snapshot5>http://img.gamefaqs.net/screens/b/d/3/gfs_155432_2_1.jpg</snapshot5>
					<snapshot6>http://img.gamefaqs.net/screens/1/0/3/gfs_155432_2_2.jpg</snapshot6>
					<snapshot7>http://img.gamefaqs.net/screens/8/b/3/gfs_155432_2_3.jpg</snapshot7>
					<snapshot8>http://img.gamefaqs.net/screens/4/a/3/gfs_155432_2_4.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/130107-f-1-spirit-the-road-to-formula-1-msx-screenshot-title-screen.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/130108-f-1-spirit-the-road-to-formula-1-msx-screenshot-intro-screen.jpg</snapshot10>
			</game>
			<game name="Aleph Ba Ta (Arab)">
					<description>Aleph Ba Ta (Arab)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2Fabcar.zip" size="20719"/>
					<releasedate>01/01/1986</releasedate>
					<studio>Al Alamiah</studio>
					<plot>This third-person racing game featuring Formula 1 cars and circuits. Besides F1 you can also choose to race a stock car, drive a rally, an endurance race or race F3 or F3000.There is a two player mode. The difficulty level can be set, and the number of laps is variable and you can select the track you want to race.The field includes ready made and custom made cars (you can select engine, tires, suspension). Avoiding the slower cars you come up to lap can be crucial.</plot>
					<genre>Racing / Driving</genre>
					<releasedate>1987</releasedate>
					<nplayers>1-2s</nplayers>
					<boxart1>http://www.mobygames.com/images/covers/l/80194-f-1-spirit-the-road-to-formula-1-msx-front-cover.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/80195-f-1-spirit-the-road-to-formula-1-msx-back-cover.jpg</boxart2>
					<snapshot1>http://www.mobygames.com/images/shots/l/130107-f-1-spirit-the-road-to-formula-1-msx-screenshot-title-screen.jpg</snapshot1>
					<snapshot2>http://www.mobygames.com/images/shots/l/130108-f-1-spirit-the-road-to-formula-1-msx-screenshot-intro-screen.jpg</snapshot2>
					<snapshot3>http://www.mobygames.com/images/shots/l/130109-f-1-spirit-the-road-to-formula-1-msx-screenshot-one-or-two.jpg</snapshot3>
					<snapshot4>http://www.mobygames.com/images/shots/l/130110-f-1-spirit-the-road-to-formula-1-msx-screenshot-stock-car.jpg</snapshot4>
					<snapshot5>http://www.mobygames.com/images/shots/l/130111-f-1-spirit-the-road-to-formula-1-msx-screenshot-watch-out.jpg</snapshot5>
					<snapshot6>http://www.mobygames.com/images/shots/l/130112-f-1-spirit-the-road-to-formula-1-msx-screenshot-ready-or-original.jpg</snapshot6>
					<snapshot7>http://www.mobygames.com/images/shots/l/130113-f-1-spirit-the-road-to-formula-1-msx-screenshot-alternate.jpg</snapshot7>
					<snapshot8>http://www.mobygames.com/images/shots/l/130114-f-1-spirit-the-road-to-formula-1-msx-screenshot-futuristic.jpg</snapshot8>
					<snapshot9>http://www.mobygames.com/images/shots/l/130116-f-1-spirit-the-road-to-formula-1-msx-screenshot-a1-spirit.jpg</snapshot9>
					<snapshot10>http://www.mobygames.com/images/shots/l/130117-f-1-spirit-the-road-to-formula-1-msx-screenshot-select-your.jpg</snapshot10>
			</game>
			

			
			<game name="ABC (Arab)">
					<description>ABC (Arab)</description>
					<system>msx1_cart</system>
					<rom name="msx1_cart.zip/MESS%200.151%20Software%20List%20ROMs%2Fmsx1_cart%2Fabcen.zip" size="18410"/>
					<releasedate>01/01/1987</releasedate>
					<studio>Al Alamiah</studio>
					<plot>This third-person racing game featuring Formula 1 cars and circuits. Besides F1 you can also choose to race a stock car, drive a rally, an endurance race or race F3 or F3000.There is a two player mode. The difficulty level can be set, and the number of laps is variable and you can select the track you want to race.The field includes ready made and custom made cars (you can select engine, tires, suspension). Avoiding the slower cars you come up to lap can be crucial.</plot>
					<genre>Racing / Driving</genre>
					<releasedate>1987</releasedate>
					<nplayers>1-2s</nplayers>
					<boxart1>http://www.mobygames.com/images/covers/l/80194-f-1-spirit-the-road-to-formula-1-msx-front-cover.jpg</boxart1>
					<boxart2>http://www.mobygames.com/images/covers/l/80195-f-1-spirit-the-road-to-formula-1-msx-back-cover.jpg</boxart2>
					<snapshot1>http://www.mobygames.com/images/shots/l/130107-f-1-spirit-the-road-to-formula-1-msx-screenshot-title-screen.jpg</snapshot1>