<?xml version="1.0" ?>
<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT title_clean (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT perspective (#PCDATA)>
		<!ELEMENT rating (#PCDATA)>
		<!ELEMENT ESRB (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT thegamesdb_id (#PCDATA)>
		<!ELEMENT gamefaqs_url (#PCDATA)>
		<!ELEMENT moby_url (#PCDATA)>
		<!ELEMENT consolegrid_url (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>		
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
<datafile>
	<header>
		<emu_name>Internet Archive Best Of - PS1</emu_name>
		<emu_parser>NoIntro_parser.xml</emu_parser>
		<emu_description>PlayStation</emu_description>
		<emu_category>Top 50</emu_category>
		<emu_version>02222017</emu_version>
		<emu_date>02/22/2017</emu_date>
		<emu_author>redump</emu_author>
		<emu_homepage>http://redump.org/</emu_homepage>
		<emu_baseurl>https://archive.org/download/</emu_baseurl>
		<emu_launcher>external</emu_launcher>
		<emu_ext_launch_cmd>"%APP_PATH%\retroarch.exe" %NETPLAY_COMMAND% -L "%APP_PATH%\cores\pcsx_rearmed_libretro.dll" "%ROM_PATH%"</emu_ext_launch_cmd>
		<emu_downloadpath>default</emu_downloadpath>
		<emu_postdlaction>convert_zip_m3u</emu_postdlaction>
		<emu_comment>The PlayStation 1 was released in 1994.  Over 20 years ago!  Even though that's ancient compared to todays systems, everyone acknowledges that the original PlayStation was an important and well-supported console.[CR][CR]Whether the PlayStation was pumping out beautiful sprites or 3D polygons, the experiences it made possible are some of gaming's greatest. These 50 titles capture the PS1's spirit of new and exciting frontiers - and even after all these years, they still (mostly) hold up thanks to their exemplary gameplay. Take a trip down memory lane with us as we recall the best PlayStation games of all time...</emu_comment>
			<emu_thumb>special://home/addons/plugin.program.iarl/resources/skins/Default/media/bestof_PS1.jpg</emu_thumb>
			<emu_banner>special://home/addons/plugin.program.iarl/resources/skins/Default/media/bestof_PS1_banner.jpg</emu_banner>
			<emu_fanart>http://pre06.deviantart.net/832b/th/pre/f/2012/351/6/3/ps1_all_stars___wallpaper_by_dashyster-d5od3l7.jpg</emu_fanart>
			<emu_logo>http://vignette2.wikia.nocookie.net/logopedia/images/b/be/PlayStation_console.png</emu_logo>
			<emu_trailer>dXSTAj9tlhE</emu_trailer>
		</header>
			<game name="Syphon Filter (USA) (v1.1)">
				<description>50.  Syphon Filter</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Syphon%20Filter%20%28USA%29%20%28v1.1%29.zip" size="435689544" />
				<title_clean>Syphon Filter</title_clean>
				<plot>There's a moment in Syphon Filter where we are tasked with killing someone while he stands next to his assistant. Nothing out of the ordinary, but here's the catch: Not only can we not kill the assistant, we can't even let the assistant know we're the ones killing the target. Somehow, some way, we have to concoct a method to kill his guy with no trace of our involvement. How the hell are we going to do that?[CR][CR]This is the beauty of Syphon Filter. There are more out-of-the-box moments like this here than in most other games we've played. Scenes like the one above kept us wondering how the game would challenge us next, inducing the "just one more mission" feeling that raise games to higher echelons of quality. Before Sam Fisher there was Syphon Filter, and we loved every second.</plot>
				<releasedate>4/4/1999</releasedate>
				<year>1999</year>
				<genre>Action, Strategy</genre>
				<studio>989 Studios</studio>
				<nplayers>1</nplayers>
				<perspective>1st-Person</perspective>
				<rating>3.8</rating>
				<ESRB>T - Teen</ESRB>
				<thegamesdb_id>7808</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/syphon-filter</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/syphon-filter/3030-1248/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/3950</consolegrid_url>
				<boxart1>http://static.giantbomb.com/uploads/scale_large/8/87790/2154881-box_sfilter.png</boxart1>
				<boxart2>http://i.imgur.com/vrx5g1k.png</boxart2>
				<boxart3>http://i.imgur.com/ebm8yJG.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/103603-syphon-filter-playstation-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/59156-syphon-filter-playstation-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/176442-syphon-filter-playstation-media.jpg</boxart6>
				<snapshot1>http://www.mobygames.com/images/shots/l/164431-syphon-filter-playstation-screenshot-intro-lian-examines-someone.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/164432-syphon-filter-playstation-screenshot-aiming-at-an-unsuspecting.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/164433-syphon-filter-playstation-screenshot-the-map-always-shows.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/164434-syphon-filter-playstation-screenshot-the-shotgun-is-very-effective.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/164435-syphon-filter-playstation-screenshot-under-attack.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/164436-syphon-filter-playstation-screenshot-in-the-subway-the-green.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/164437-syphon-filter-playstation-screenshot-in-the-subway-after-a.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/164438-syphon-filter-playstation-screenshot-climbing.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/164439-syphon-filter-playstation-screenshot-in-the-park-protecting.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/164440-syphon-filter-playstation-screenshot-the-taser-can-even-kill.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/7808-1.jpg</fanart1>
				<banner1>http://i.imgur.com/SZpGJBX.jpg</banner1>
			</game>
			<game name="Bloody Roar II (USA)">
				<description>49.  Bloody Roar II</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Bloody%20Roar%20II%20%28USA%29.zip" size="317978721" />
				<title_clean>Bloody Roar II</title_clean>
				<plot>The PS served as fertile ground for the fighting genre, as many of the top names in virtual fisticuffs got their start on Sony's first console. Some franchises, however, haven't been able to break the current mold despite being incredible games. Bloody Roar, and its martial-artists-turning-into-animals premise, is a prime example.[CR][CR]Bloody Roar 2 serves as the cream of the bloody crop. A sound fighting system, plenty of modes and match types, and impressive graphics make this one of the top fighters on the entire system. Of course, being able to transform from a human to a kung-fu tiger or a deadly ninja mole is always a good thing.</plot>
				<releasedate>26/5/1999</releasedate>
				<year>1999</year>
				<genre>Action</genre>
				<studio>Sony Computer Entertainment America, Inc.</studio>
				<nplayers>1-2 Alt</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>4.0</rating>
				<ESRB>T - Teen</ESRB>
				<thegamesdb_id>2506</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/bloody-roar-ii</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/bloody-roar-ii/3030-11876/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/10817</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/2506-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/2506-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/156783-bloody-roar-ii-playstation-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/319813-bloody-roar-ii-playstation-media.jpg</boxart4>
				<snapshot1>http://thegamesdb.net/banners/screenshots/2506-1.jpg</snapshot1>
				<snapshot2>http://thegamesdb.net/banners/screenshots/2506-2.jpg</snapshot2>
				<snapshot3>http://thegamesdb.net/banners/screenshots/2506-3.jpg</snapshot3>
				<snapshot4>http://thegamesdb.net/banners/screenshots/2506-4.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/545854-bloody-roar-ii-playstation-screenshot-title-screen.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/260718-bloody-roar-ii-playstation-screenshot-title-screen-japanese.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/260719-bloody-roar-ii-playstation-screenshot-character-selection.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/260720-bloody-roar-ii-playstation-screenshot-pre-match-versus-screen.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/545855-bloody-roar-ii-playstation-screenshot-yugo-is-slashing-jenny.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/545856-bloody-roar-ii-playstation-screenshot-alice-s-victory-pose.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/2506-1.jpg</fanart1>
				<fanart2>http://thegamesdb.net/banners/fanart/original/2506-2.jpg</fanart2>
				<fanart3>http://thegamesdb.net/banners/fanart/original/2506-3.jpg</fanart3>
				<fanart4>http://thegamesdb.net/banners/fanart/original/2506-4.jpg</fanart4>
				<banner1>http://i.imgur.com/dUIytRk.png</banner1>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/2506.png</clearlogo1>
			</game>
			<game name="Star Ocean - The Second Story (USA)">
				<description>48.  Star Ocean - The Second Story</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Star%20Ocean%20-%20The%20Second%20Story%20%28USA%29%20%28Disc%201%29.zip" size="432018709" />
				<rom name="RedumpSonyPlayStationAmerica20160617/Star%20Ocean%20-%20The%20Second%20Story%20%28USA%29%20%28Disc%202%29.zip" size="548788229" />
				<title_clean>Star Ocean - The Second Story</title_clean>
				<plot>There's nothing we like more than being able to craft an unique adventure. That's why series like The Elder Scrolls are so successful: While the story may remain the same, no two people played through it the same way.[CR][CR]Enix gave us a fantastic example of this with Star Ocean: The Second Story. Sure, the 40-hour story didn't change from playthrough to playthrough, but the way we interacted with the world did. Item creation allowed us to forge equipment to fit our needs. Real-time combat, coupled with the inclusion of group spells and attack combos, made fighting each battle more fluid and unique. All of these things make Star Ocean: The Second Story a classic RPG worthy of any RPG fan's collection.</plot>
				<releasedate>6/8/1999</releasedate>
				<year>1998</year>
				<genre>Action, RPG, Strategy</genre>
				<studio>Sony Computer Entertainment America, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.8</rating>
				<ESRB>E - Everyone</ESRB>
				<thegamesdb_id>13577</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/star-ocean-the-second-story</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/star-ocean-the-second-story/3030-620/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/3892</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/13577-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/13577-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/18929-star-ocean-the-second-story-playstation-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/18930-star-ocean-the-second-story-playstation-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/130495-star-ocean-the-second-story-playstation-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/149693-star-ocean-the-second-story-playstation-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/309539-star-ocean-the-second-story-playstation-media.jpg</boxart7>
				<boxart8>http://www.mobygames.com/images/covers/l/319963-star-ocean-the-second-story-playstation-media.jpg</boxart8>
				<snapshot1>http://www.mobygames.com/images/shots/l/79669-star-ocean-the-second-story-playstation-screenshot-you-get.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/79670-star-ocean-the-second-story-playstation-screenshot-standard.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/79671-star-ocean-the-second-story-playstation-screenshot-walking.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/79672-star-ocean-the-second-story-playstation-screenshot-a-surprise.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/79673-star-ocean-the-second-story-playstation-screenshot-he-s-toast.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/796214-star-ocean-the-second-story-playstation-screenshot-the-title.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/796215-star-ocean-the-second-story-playstation-screenshot-after-the.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/796216-star-ocean-the-second-story-playstation-screenshot-this-is.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/796217-star-ocean-the-second-story-playstation-screenshot-this-is.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/796218-star-ocean-the-second-story-playstation-screenshot-in-the.jpg</snapshot10>
				<banner1>http://i.imgur.com/OWOXUXw.jpg</banner1>
			</game>
			<game name="Alundra (USA) (v1.1)">
				<description>47.  Alundra</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Alundra%20%28USA%29%20%28v1.1%29.zip" size="346741896" />
				<title_clean>Alundra</title_clean>
				<plot>We all have a masochistic side. There's a part of us that, no matter how difficult a game may be, even if it drives us stark raving mad, we will be victorious. We may have less hair on our head, but we beat the game, dammit.[CR][CR]Alundra will test every single one of your limits. You will curse. You will cry. Controllers will be thrown. However, every second of the game is absolutely worth it. A fantastic story, gameplay mirroring A Link to the Past, and a tremendous soundtrack will all soothe the inevitable bloody knuckles you'll get from punching a wall. Did we mention it's hard?</plot>
				<releasedate>7/1/1998</releasedate>
				<year>1997</year>
				<genre>Action, Adventure, RPG</genre>
				<studio>Working Designs</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.7</rating>
				<ESRB>T - Teen</ESRB>
				<thegamesdb_id>495</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/alundra</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/alundra/3030-5570/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/11008</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/495-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/495-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/178043-alundra-playstation-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/60493-alundra-playstation-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/58099-alundra-playstation-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/107723-alundra-playstation-media.jpg</boxart6>
				<snapshot1>http://thegamesdb.net/banners/screenshots/495-1.jpg</snapshot1>
				<snapshot2>http://thegamesdb.net/banners/screenshots/495-2.jpg</snapshot2>
				<snapshot3>http://thegamesdb.net/banners/screenshots/495-3.jpg</snapshot3>
				<snapshot4>http://thegamesdb.net/banners/screenshots/495-4.jpg</snapshot4>
				<snapshot5>http://thegamesdb.net/banners/screenshots/495-5.jpg</snapshot5>
				<snapshot6>http://thegamesdb.net/banners/screenshots/495-6.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/26044-alundra-playstation-screenshot-alundra.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/26045-alundra-playstation-screenshot-monsters-from-the-intro-anime.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/26046-alundra-playstation-screenshot-meia.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/26047-alundra-playstation-screenshot-a-sinking-town.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/495-1.jpg</fanart1>
				<fanart2>http://thegamesdb.net/banners/fanart/original/495-2.jpg</fanart2>
				<fanart3>http://thegamesdb.net/banners/fanart/original/495-3.jpg</fanart3>
				<banner1>http://i.imgur.com/96i0Mzt.png</banner1>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/495.png</clearlogo1>
			</game>
			<game name="Valkyrie Profile (USA)">
				<description>46.  Valkyrie Profile</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Valkyrie%20Profile%20%28USA%29%20%28Disc%201%29.zip" size="552532628" />
				<rom name="RedumpSonyPlayStationAmerica20160617/Valkyrie%20Profile%20%28USA%29%20%28Disc%202%29.zip" size="561274431" />
				<title_clean>Valkyrie Profile</title_clean>
				<plot>"A side-scrolling RPG? Preposterous! Those two genres don't fit together! This will never work!" That's how many felt before Valkyrie Profile proved them wrong. Not only does a side-scrolling RPG work, it's one of the best games on the PS.[CR][CR]Recruiting heroes to fight for Odin during Ragnarok sounds epic on its own, and in practice it meets every expectation. The gorgeous hand-drawn art style and engaging battle system will keep any RPG fan playing for days. Plus, Valkyrie Profile is one of the few games to reward you for switching to Hard Mode, unlocking characters and dungeons only to those who decide to brave the hardest setting. After putting ourselves through that gauntlet, we say bring on Ragnarok. We need a break.</plot>
				<releasedate>29/8/2000</releasedate>
				<year>1999</year>
				<genre>Action, Adventure, RPG, Strategy</genre>
				<studio>Enix Corporation</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.6</rating>
				<ESRB>T - Teen</ESRB>
				<thegamesdb_id>12403</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/valkyrie-profile</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/valkyrie-profile/3030-11602/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/6894</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/12403-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/12403-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/17613-valkyrie-profile-playstation-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/17614-valkyrie-profile-playstation-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/242313-valkyrie-profile-playstation-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/242314-valkyrie-profile-playstation-media.jpg</boxart6>
				<snapshot1>http://www.mobygames.com/images/shots/l/217836-valkyrie-profile-playstation-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/217837-valkyrie-profile-playstation-screenshot-intro.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/217838-valkyrie-profile-playstation-screenshot-not-very-common-in.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/217839-valkyrie-profile-playstation-screenshot-prologue-lucien-is.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/217840-valkyrie-profile-playstation-screenshot-valhalla.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/217841-valkyrie-profile-playstation-screenshot-meeting-odin.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/556462-valkyrie-profile-playstation-screenshot-an-early-battle-against.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/556463-valkyrie-profile-playstation-screenshot-emotional-stories.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/556464-valkyrie-profile-playstation-screenshot-an-early-boss-battle.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/556465-valkyrie-profile-playstation-screenshot-world-map-navigation.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/12403-1.jpg</fanart1>
				<fanart2>http://thegamesdb.net/banners/fanart/original/12403-2.jpg</fanart2>
				<fanart3>http://thegamesdb.net/banners/fanart/original/12403-3.jpg</fanart3>
				<fanart4>http://thegamesdb.net/banners/fanart/original/12403-4.jpg</fanart4>
				<fanart5>http://thegamesdb.net/banners/fanart/original/12403-5.jpg</fanart5>
				<fanart6>http://thegamesdb.net/banners/fanart/original/12403-6.jpg</fanart6>
				<fanart7>http://thegamesdb.net/banners/fanart/original/12403-7.jpg</fanart7>
				<banner1>http://i.imgur.com/hFp0mee.png</banner1>
			</game>
			<game name="Need for Speed III - Hot Pursuit (USA)">
				<description>45.  Need for Speed III - Hot Pursuit</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Need%20for%20Speed%20III%20-%20Hot%20Pursuit%20%28USA%29.zip" size="426492770" />
				<title_clean>Need for Speed III - Hot Pursuit</title_clean>
				<plot>The original Need for Speed included a police ticketing system that made racing a little more dangerous. We didn't want to get arrested and lose our sweet ride, who would? The mechanic was abandoned in NFS2, but EA decided to make it the main focus of the third title, and a new classic was born.[CR][CR]Need for Speed III: Hot Pursuit gave us a whole new perspective on adrenaline: Racing at top speeds was enough, but now fleeing for our freedom from the oppressive police military complex? That was a feeling sorely missed in the second Need for Speed game. It also allowed us to live out our reckless, seat-of-our-pants criminal fantasies without actually doing anything illegal, and for that we will always be thankful.</plot>
				<releasedate>25/3/1998</releasedate>
				<year>1998</year>
				<genre>Driving, Racing, Simulation</genre>
				<studio>Electronic Arts, Inc.</studio>
				<nplayers>1-2 Alt</nplayers>
				<perspective>1st-Person</perspective>
				<rating>2.6</rating>
				<ESRB>E - Everyone</ESRB>
				<thegamesdb_id>1012</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/need-for-speed-iii-hot-pursuit</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/need-for-speed-iii-hot-pursuit/3030-5977/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/3529</consolegrid_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/1012-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/1012-1.jpg</boxart2>
				<snapshot1>http://www.mobygames.com/images/shots/l/177098-need-for-speed-iii-hot-pursuit-playstation-screenshot-just.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/177099-need-for-speed-iii-hot-pursuit-playstation-screenshot-close.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/177100-need-for-speed-iii-hot-pursuit-playstation-screenshot-don.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/177101-need-for-speed-iii-hot-pursuit-playstation-screenshot-scraping.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/177102-need-for-speed-iii-hot-pursuit-playstation-screenshot-at-the.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/177103-need-for-speed-iii-hot-pursuit-playstation-screenshot-player.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/177104-need-for-speed-iii-hot-pursuit-playstation-screenshot-watch.jpg</snapshot7>
				<snapshot8>http://static.giantbomb.com/uploads/scale_large/9/94648/1825661-nfs_3_donuts.png</snapshot8>
				<snapshot9>http://static.giantbomb.com/uploads/scale_large/0/329/1637633-7.jpg</snapshot9>
				<snapshot10>http://static.giantbomb.com/uploads/scale_large/0/329/1637632-6.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/1012-1.jpg</fanart1>
				<fanart2>http://thegamesdb.net/banners/fanart/original/1012-2.jpg</fanart2>
				<banner1>http://i.imgur.com/k31fwqC.jpg</banner1>
			</game>
			<game name="Colony Wars (USA)">
				<description>44.  Colony Wars</description>
				<rom name="RedumpSonyPlayStationAmerica20160617/Colony%20Wars%20%28USA%29%20%28Disc%201%29.zip" size="382526939" />
				<rom name="RedumpSonyPlayStationAmerica20160617/Colony%20Wars%20%28USA%29%20%28Disc%202%29.zip" size="468769450" />
				<title_clean>Colony Wars</title_clean>
				<plot>Colony Wars: Vengeance is another game that, like Alundra previously, often caused us to throw things in utter disgust. But we didn't care. The experience was enjoyable enough that a few holes in the wall wouldn't deter us one bit.[CR][CR]Part of what made Colony Wars: Vengeance so stressful was the branching storyline being directly affected by the outcome of a mission. One failed mission could result in us viewing the worst ending in the game, and we had to pick up and start all over again just to see an improved outcome. We didn't know what missions were more important than others, so all we could do is try and pass them all. Sure, our gaming rooms ended up looking like Swiss cheese, but it was totally worth it.</plot>
				<releasedate>5/11/1997</releasedate>
				<year>1997</year>
				<genre>Action, Simulation</genre>
				<studio>Psygnosis Limited</studio>
				<nplayers>1</nplayers>
				<perspective>1st-Person</perspective>
				<rating>3.9</rating>
				<ESRB>E - Everyone</ESRB>
				<thegamesdb_id>8366</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/playstation/colony-wars</mobygames_url>
				<giantbomb_url>http://www.giantbomb.com/colony-wars/3030-4830/</giantbomb_url>
				<consolegrid_url>http://consolegrid.com/games/11181</consolegrid_url>